version: '3.2'
services:
  kafka:
    image: debezium/kafka:0.8
    hostname: kafka
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181      
    ports:
      - 9092:9092
    networks:
      - streaming

networks:
  streaming:
    driver: overlay
    attachable: true
  func_functions:
    external: true
