version: '3.2'
services:
  zookeeper:
    image: debezium/zookeeper:0.8
    hostname: zookeeper
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    networks:
      - streaming
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888

networks:
  streaming:
    driver: overlay
    attachable: true
  func_functions:
    external: true
